export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const BASEINFO = 'BASEINFO'

export const SHOWTOAST = 'SHOWTOAST'
export const HIDETOAST = 'HIDETOAST'

export const SHOWLOADING = 'SHOWLOADING'
export const HIDELOADING = 'HIDELOADING'

export const USERFORMTITLE = 'USERFORMTITLE'
export const USERFORMTYPE = 'USERFORMNAME'
export const USERFORMNAME = 'USERFORMNAME'
export const USERFORMVALUE = 'USERFORMVALUE'
